# Project information
site_name: CMS Open Data Guide
site_description: 'CMS Open Data Guide'
site_url: 'https://cms-opendata-guide.web.cern.ch/'

# Repository
repo_name: 'cms-opendata-guide'
repo_url: 'https://github.com/cernopendata/cms-opendata-guide'

# Structure
nav:
    - Home: index.md
    - 'Computing Tools':
        - 'CERN Open Data Portal': tools/cernportal.md
        - 'CMS Open Data': tools/cmsopendata.md
        - 'CMS Twiki': tools/cmstwiki.md
        - 'UNIX': tools/unix.md
        - 'ROOT': tools/root.md
        - 'C++ and Python': tools/cppandpython.md
        - 'Git': tools/git.md
        - 'Docker': tools/docker.md
        - 'Virtual Machines': tools/virtualmachines.md
    - 'CMSSW':
        - 'Overview': cmssw/cmsswoverview.md
        - 'Data Model': cmssw/cmsswdatamodel.md
        - 'Analyzers': cmssw/cmsswanalyzers.md
        - 'Configuration': cmssw/cmsswconfigure.md
        - 'Conditions Data': cmssw/cmsswconditions.md
    - 'Analysis':
        - 'Data and Simulation':
            - 'Collision Data': analysis/datasim/collisiondata.md
            - 'MC Simulations': analysis/datasim/mcsimulations.md
            - 'Event Generation': analysis/datasim/eventgeneration.md
        - 'Selection':
            - 'Triggers': analysis/selection/triggers.md
            - 'Physics Objects': analysis/selection/objects.md
            - 'Physics Objects ID': analysis/selection/objectid.md
        - 'Luminosity': 
            - 'Luminosity': analysis/luminosity/lumi.md
        - 'Backgrounds':
            - 'Techniques': analysis/backgrounds/techniques.md
            - 'QCD Estimation': analysis/backgrounds/qcdestimation.md
            
        - 'Systematics':
            - 'Luminosity Uncertainties': analysis/systematics/lumiuncertain.md
            - 'MC Uncertainty': analysis/systematics/mcuncertain.md
            - 'Object Uncertainty': analysis/systematics/objectsuncertain.md
            - 'Pileup Uncertainty': analysis/systematics/pileupuncertain.md
        - 'Interpretation':
            - 'Statistics': analysis/interpretation/stats.md
            - 'Upper-limit Calculations': analysis/interpretation/limits.md 
    - FAQ: faq.md
    - About: about.md

# Configuration
theme:
    name: material
    palette:
      scheme: 'default'
      primary: 'indigo'
      accent:
    font:
      text: 'Lato'
    icon:
      repo: 'fontawesome/brands/github'
    logo: 'images/cmslogo.png'
    favicon: 'images/favicon.ico'
    feature:
      tabs: 'true'

# Customization
extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
    - admonition
    - codehilite:
        guess_lang: false
    - toc:
        permalink: true

# Plugins
plugins:
  - search
  - awesome-pages:
      collapse_single_pages: false
